### 3.3 다차원 배열의 계산

##### 3.3.1 다차원 배열

In [2]:
#지금까지 보아온 1차원 배열
import numpy as np
A=np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [7]:
# 배열의 차원 수
np.ndim(A)

1

In [5]:
# 배열의 형상
A.shape

(4,)

In [6]:
A.shape[0]

4

In [10]:
#2차원 배열 
B=np.array([[1,2],[3,4],[5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
np.ndim(B)

2

In [12]:
B.shape
# (행,열)의 결과로 출력

(3, 2)

##### 3.2.2 행렬의 내적(행렬 곱)

In [13]:
A=np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [15]:
B=np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [16]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

np.dot()은 넘파이 배열 2개를 인수로 받아 그 내적을 반환함. 

일반적인 연산과 달리 행렬의 곱에서는 연산 순서가 다르면 결과도 다름을 유의하기

행렬 A와 B의 내적에서, A의 열수와 B의 행수가 같아야함

In [18]:
A=np.array([[1,2],[3,4],[5,6]])
A.shape

(3, 2)

In [19]:
B=np.array([7,8])
B.shape

(2,)

In [22]:
np.dot(A,B)

array([23, 53, 83])

##### 3.3.3 신경망의 내적

In [23]:
#X와 W의 대응하는 차원의 원소 수가 같아야 함
X=np.array([1,2])
X.shape

(2,)

In [24]:
W=np.array([[1,3,5],[2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [25]:
W.shape

(2, 3)

In [26]:
Y=np.dot(X,W)
print(Y)

[ 5 11 17]
